### ISSUE TITLE
[Feature]: Add the solution of any LEET code

### ISSUE THREAD

**Issue by DugarRishab** [DugarRishab/Algo.io#1]
## Description: 
- Add the solution to any Leet Code question
- The solution must not already be present in this repo
- If submitting an alternative to any existing solution, please mark it as [Alternative]

## Eligibility Criteria: 
- [ ] The solution must pass all the tests on Leet code. Please provide a screenshot to prove the same
- [ ] If it is an alternative, then it must have a better time complexity than the previous solution.

**Comment by sarthak17jain** [comment]
Please assign me this issue.

**Comment by aanya963** [comment]
Please assign this issue, I'll solve Q7 reverse integer.

**Comment by DugarRishab** [comment]
Hey @sarthak17jain @Aanya9693. Thanks for showing your interest in this issue. I am assigning this issue to both of you. @sarthak17jain, please remember to solve other questions as @Aanya9693 will be solving Q7.

**Comment by vivek-dhiman** [comment]
Please assign the issue to me. I wish to add solutions to some interesting questions on Leetcode, explained with comments.

**Comment by sarthak17jain** [comment]
> Hey @sarthak17jain @Aanya9693. Thanks for showing your interest in this issue. I am assigning this issue to both of you. @sarthak17jain, please remember to solve other questions as @Aanya9693 will be solving Q7.

Sure, I'll be solving 98. Validate Binary Search Tree.

**Comment by DugarRishab** [comment]
Hey, @vivek-dhiman Thanks for showing interest. I will assign this to you too.

**Comment by DugarRishab** [comment]
Hey everyone, 
I have updated the description. Please go through the updated description and update you pull requests accordingly. 
Sorry for the inconvenience caused.

**Comment by gaurang7goel** [comment]
hi, i would also like to contribute to this issue

**Comment by DugarRishab** [comment]
Hey, @gaurang7goel thanks for showing interest. I will add to the assignees. Please remember to go through the README.md and description of this issue

**Comment by gaurang7goel** [comment]
Sure, thanks.

**Comment by hardiksharma11** [comment]
Hiii, can I contribute to this issue..

**Comment by DugarRishab** [comment]
Hii @hardiksharma11, sure you can contribute to this. I will assign you now.

**Comment by anshrusia200** [comment]
Hey, can I contribute? I will do Q118 Pascal's triangle.

**Comment by DugarRishab** [comment]
Hey, @anshrusia200. yes you can contribute.

**Comment by anshrusia200** [comment]
Sure. @DugarRishab I have created a PR. Please review.

**Comment by DugarRishab** [comment]
Everyone, Following files has been added to this repo: 
1. CONTRIBUTING.md
2. CODE_OF_CONDUCT.md
3. pull_request_template.md

Please go through them. And from now on, these must be strictly followed. In case of PR templates, I believe that the template will be already visible when creating a new PR. 
Thank you !!

**Comment by deven-533** [comment]
Hello Sir Can I also Contribute here please assign this issue to me

**Comment by DugarRishab** [comment]
> 

Yes, @deven-533 You can contribute to this issue. I will assign you now.
