### ISSUE TITLE
[FEATURE]:  Add solution to Q1 to Q10 in Python

### ISSUE THREAD

**Issue by DugarRishab** [DugarRishab/Algo.io#13]
## Description: 
- To increase the variety of solutions, add only Python solution of Q1 to Q10 of Leet Code.

## Questions: 
- [x] Q1 
- [x] Q2
- [x] Q3
- [x] Q4
- [x] Q5
- [x] Q6
- [x] Q7
- [x] Q8
- [x] Q9
- [x] Q10

## Eligibility Criteria: 
- Code must be in python
- Code must have passed all the tests in Leet code. Please provide the screenshot as a proof

## Note: 
- Pull Requests will only be accepted from assigned people. So get yourself assigned first.

**Comment by Hackvm** [comment]
Hello, I would like to contribute to this. Can you assign me this for the hacktoberfest?

**Comment by DugarRishab** [comment]
Yes, @Vivek-mishra-2002 go ahead an contribute

**Comment by Hackvm** [comment]
Thank U

**Comment by rising-star2712** [comment]
hello , I would like to contribute , could i be assigned this for hacktober fest

**Comment by DugarRishab** [comment]
@rising-star2712 I am assigning you to this issue now.

**Comment by Ishh1505** [comment]
@DugarRishab could you please assign this issue to me as well

**Comment by DugarRishab** [comment]
Everyone, Following files has been added to this repo: 
1. CONTRIBUTING.md
2. CODE_OF_CONDUCT.md
3. pull_request_template.md

Please go through them. And from now on, these must be strictly followed. In case of PR templates, I believe that the template will be already visible when creating a new PR. 
Thank you !!

**Comment by DugarRishab** [comment]
Hey @Vivek-mishra-2002 and @rising-star2712, have any of you made any PRs related to this issue?

**Comment by rising-star2712** [comment]
@DugarRishab  working on it , also having a question that which q1 to q10 of  Leetcode are we supposed to solve

**Comment by DugarRishab** [comment]
> @DugarRishab working on it , also having a question that which q1 to q10 of Leetcode are we supposed to solve

Any of the 10 questions. Do whatever questions you can

**Comment by rising-star2712** [comment]
ok working on it

**Comment by DugarRishab** [comment]
Everyone working on this issue, Please make separate PRs for each question. This way your PRs will not clash

**Comment by artemis-i-guess** [comment]
Assign me Q9 of Leetcode in Python, thank you .

**Comment by DugarRishab** [comment]
> Assign me Q9 of Leetcode in Python, thank you .

assigning you now

**Comment by rising-star2712** [comment]
@DugarRishab do i have to submit any 10 questions with solution or only 1

**Comment by rising-star2712** [comment]
@DugarRishab sorry for not seeing your earlier message , I made a PR with 3  questions after seeing ur msg

**Comment by vatsal9117** [comment]
Hey @DugarRishab  i would like to contribute it please assign me,

**Comment by DugarRishab** [comment]
@vatsal9117 i will assign you now

**Comment by DugarRishab** [comment]
@rising-star2712 I don't know if you have noticed yet, but I requested some changes on your PR.

**Comment by Faizan96322** [comment]
hey, I would like to contribute Q10 of leetcode!, please assign me this task!

**Comment by DugarRishab** [comment]
> hey, I would like to contribute Q10 of leetcode!, please assign me this task!

Yeah, I will assign you now

**Comment by RP2025** [comment]
Hey, I would like to contribute Q2 , Q3 Q5 and Q7 of leetcode. Please assign me this task

**Comment by DugarRishab** [comment]
> Hey, I would like to contribute Q2 , Q3 Q5 and Q7 of leetcode. Please assign me this task

Yeah, assigning you now.

**Comment by DugarRishab** [comment]
> Hey, I would like to contribute Q2 , Q3 Q5 and Q7 of leetcode. Please assign me this task

Looks like most of the questions are already solved. Only Q6 left.

**Comment by RP2025** [comment]
I would like to contribute to question 6 , Please assign me that

**Comment by DugarRishab** [comment]
> I would like to contribute to question 6 , Please assign me that

You are already assigned. Go ahead and make you PR.

**Comment by rising-star2712** [comment]
@DugarRishab how should I add images in description , first time contributing so pls help

**Comment by DugarRishab** [comment]
> @DugarRishab how should I add images in description , first time contributing so pls help

- copy and paste the image  in the description box 
- You can also drag and drop the image

**Comment by rising-star2712** [comment]
> > @DugarRishab how should I add images in description , first time contributing so pls help
> 
> * copy and paste the image  in the description box
> * You can also drag and drop the image

Done required changes pls check @DugarRishab

**Comment by rising-star2712** [comment]
@DugarRishab could u help out how do we do the new commit thing , like exactly I am not getting what i should be doing
