### ISSUE TITLE
[Feature]: Add solution for Question 2 of Leet Code

### ISSUE THREAD

**Issue by DugarRishab** [DugarRishab/Algo.io#2]
## Description:

- Add the solution to Question 2 on Leet Code

## Eligibility Criteria: 

- [ ] Solution must pass all the tests on Leet Code. Provide a screenshot as proof.
- [ ]  If the solution is already present, then the new solution must have a better time complexity.

**Comment by deven-533** [comment]
Hi, I would like to take up this issue for Hacktoberfest 2022, Kindly Please Assign this issue to me.

**Comment by Ishantgarg-web** [comment]
Hey, please assign this task to me

**Comment by joanjeremiah** [comment]
Hi, I have been doing competitive coding for years. I would like to take this issue. Kindly assign it to me

**Comment by DugarRishab** [comment]
According to fcfs, I am assigning you to this issue to @deven-533 
Sry @Ishantgarg-web and @joanjeremiah, you can look at other issues. More issues are coming up.

**Comment by DugarRishab** [comment]
Someone already sent me a Pull request regarding this issue.

**Comment by deven-533** [comment]
Sir but I was Assigned this Issue and was ready with my pull request, and you accepted the pull request by @vivek-dhiman .

**Comment by DugarRishab** [comment]
@deven-533 I understand. Just because I closed this issue, doesn't mean I will not accept a new solution.  Send your PR right away
