### ISSUE TITLE
[BUG]: Incorrect Solution to Q5

### ISSUE THREAD

**Issue by DugarRishab** [DugarRishab/Algo.io#4]
## Description: 
- The solution to Leet code question Q5 is getting a TLE error.
- A new solution is needed which can solve this question within the time constraints.

## Eligibility Criteria: 
- [ ] The solution must pass all the tests on the Leet code. Provide a screenshot to prove the same

**Comment by NiketBahety** [comment]
I have the correct solution for this question. Please assign this to me.

**Comment by DugarRishab** [comment]
Thanks, @NiketBahety. assigning this to you
