### ISSUE TITLE
[FEATURE]: Design a Logo for Algo.io

### ISSUE THREAD

**Issue by DugarRishab** [DugarRishab/Algo.io#75]
## Description

Design a *minimal* Logo. 

## Requirements
- [x] The logo must match the present color theme. 
- [x] Provide the logo in 3 variants: 
   - [x] One with black bg
   - [x] One with white bg
   - [x] One normal (*this is the main one*)

## Note: 

- In the PR, please disregard the template because it was created for other purpose. Please copy the Requirements section from this description to your PRs description and mark all that you have done. 
- Please note that this issue will not be assigned on a **first come first serve** basis, rather on credit basis by judging the repos in your profile.

**Comment by 72002sweta** [comment]
I can design the logo please assign me.

**Comment by DugarRishab** [comment]
Hey, @72002sweta. Thanks for showing interest. I will assign this issue to you now

**Comment by 72002sweta** [comment]
do I've to create a new file and upload all the images, and what are the colors you want in your logo, please provide details

**Comment by DugarRishab** [comment]
> do I've to create a new file and upload all the images, and what are the colors you want in your logo, please provide details

Yes, create a new folder inside `/client/src/assets/` and put all the files in it.

**Comment by DugarRishab** [comment]
> do I've to create a new file and upload all the images, and what are the colors you want in your logo, please provide details

Head over to ISSUE: #66 and look at the designs. Feel free to use whatever colors you like, but it must match with the vide of the page.

**Comment by 72002sweta** [comment]
done with the logo suggest any changes if you want, thankyouu.

**Comment by DugarRishab** [comment]
> done with the logo suggest any changes if you want, thankyouu.

Hey, sorry for responding do late. Please check for my comments on your PR.
